version: "3.4"
services:
  vite_docker:
    container_name: vite_docker
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - 8080:80
    tty: true
    environment:
      - DEBUG=0
      - DB_HOST=${VITE_DB_HOST}
      - DB_USER=${VITE_DB_USER}
      - DB_PASSWORD=${VITE_DB_PASSWORD}
      - DB_NAME=${VITE_DB_NAME}
      - DB_PORT=${VITE_DB_PORT}
